export { default as SkillsSection } from "./SkillsSection/SkillsSection"
export { default as ExperiencesSection } from "./ExperiencesSection/ExperiencesSection"
export { default as IntroductionSection } from "./IntroductionSection/IntroductionSection"
export { default as ProjectsSection } from "./ProjectsSection/ProjectsSection"
export { default as ContactSection } from "./ContactSection/ContactSection"
